name: Release Workflow
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Initialize NPM Config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Run Release
        run: yarn release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
